ALTER TABLE pago MODIFY COLUMN metodoPago ENUM('WEBPAY','TRANSFER','CASH','SALDO_AUTOBOX') DEFAULT 'WEBPAY';
ALTER TABLE pago MODIFY COLUMN estado ENUM('PENDING','COMPLETED','FAILED','REFUNDED') DEFAULT 'PENDING';
